### ISSUE TITLE
Pretty cool app!

### ISSUE THREAD

**Issue by yoshyosh** [enochng1/RaceMe#1]
Hey there Enoch! Is there an email I can reach you at? I work for Realm and noticed you made this app using Realm. Would love to hear more about your experience. 

This is one of the notable apps we've seen so far this month and would like to share it with the rest of the community.

**Comment by enochng1** [comment]
Hello Joseph,

This is my personal email. Thank you for reaching out and complimenting!
Very flattered. Let me know how I can share more about the development of
this app!

Cheers,
Enoch

**Comment by yoshyosh** [comment]
Sounds good I sent you a note!
