### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [enochng1/RaceMe#3]
<img width="348" alt="screen shot 2016-07-19 at 12 35 14 pm" src="https://cloud.githubusercontent.com/assets/6511079/16956053/43284332-4dad-11e6-85f3-02a282e7930c.png">
Should be something like:

> RaceMe is a run tracking + ghosting iOS mobile application.

**Comment by enochng1** [comment]
Thank you!
Will update that!
